# Generated by Django 6.0.5 on 2026-05-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                ("id_kategori", models.AutoField(primary_key=True, serialize=False)),
                ("nama_kategori", models.CharField(max_length=255)),
                ("jumlah_barang", models.IntegerField(default=0)),
                ("dibuat", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "kategori",
            },
        ),
    ]
