# Generated by Django 6.0.5 on 2026-05-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frozeria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategori",
            name="dibuat",
            field=models.DateTimeField(),
        ),
    ]
