# Generated by Django 6.0.5 on 2026-05-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frozeria", "0002_alter_kategori_dibuat"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategori",
            name="deskripsi",
            field=models.TextField(blank=True, null=True),
        ),
    ]
