# Generated by Django 6.0.5 on 2026-05-07 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frozeria", "0003_kategori_deskripsi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("id_dashboard", models.AutoField(primary_key=True, serialize=False)),
                (
                    "foto_barang",
                    models.ImageField(blank=True, null=True, upload_to="foto_barang/"),
                ),
                ("nama_barang", models.CharField(max_length=255)),
                ("satuan", models.CharField(max_length=100)),
                ("jumlah_stok", models.IntegerField(default=0)),
                ("stok_minimum", models.IntegerField(default=0)),
                (
                    "harga_jual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "harga_beli",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "berat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("lokasi_simpan", models.CharField(max_length=255)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("dibuat", models.DateTimeField(auto_now_add=True)),
                ("diupdate", models.DateTimeField(auto_now=True)),
                (
                    "kategori",
                    models.ForeignKey(
                        db_column="id_kategori",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_items",
                        to="frozeria.kategori",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard",
            },
        ),
    ]
